name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-executable:
    runs-on: windows-2022

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11' # Use the latest supported Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the executable
      - name: Build Executable
        run: |
          pyinstaller --onefile --name dotranslate main.py

      # Step 5: Upload the artifact
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: dotranslate-executable
          path: dist/dotranslate.exe